const fs = require('fs');
const assert = require('node:assert/strict');
const html = fs.readFileSync(new URL('../dist/index.html', `file://${__filename}`).pathname, 'utf8');
const buyer = 'https://forms.gle/SwiAMdvSeLEMvsv37';
const supplier = 'https://forms.gle/SwiAMdvSeLEMvsv37';
const sourceCss = fs.readFileSync(new URL('../src/styles/index.css', `file://${__filename}`).pathname, 'utf8');
assert.ok(html.includes(buyer), 'Buyer survey URL missing');
assert.ok(html.includes(supplier), 'Supplier survey URL missing');
assert.ok(html.includes('https://wa.me/2349150695747'), 'Updated Nigeria WhatsApp URL missing');
assert.ok(html.includes('+234 915 069 5747'), 'Updated Nigeria phone number missing');
assert.ok(!html.includes('martfornigeria@gmail.com'), 'Removed email address still present');
assert.ok(!html.includes('919305243422'), 'Old WhatsApp number still present');
assert.ok(!html.includes('2RJ6NG74XtLaBXy28'), 'Old buyer survey URL still present');
assert.ok(!html.includes('qpTtyupgmuiPeW4i6'), 'Old supplier survey URL still present');
assert.ok(html.includes('Illustrative preview'), 'Product concept label missing');
assert.ok(html.includes('Early research &amp; validation'), 'Early-stage positioning missing');
assert.ok(html.includes('prefers-reduced-motion') || fs.readFileSync(new URL('../dist/assets/site.css', `file://${__filename}`).pathname, 'utf8').includes('prefers-reduced-motion'), 'Reduced-motion CSS missing');
const ids = new Set([...html.matchAll(/\sid="([^"]+)"/g)].map((match) => match[1]));
const refs = [...html.matchAll(/href="#([^"]+)"/g)].map((match) => match[1]);
const missing = [...new Set(refs.filter((ref) => !ids.has(ref)))];
assert.deepEqual(missing, [], `Broken internal anchors: ${missing.join(', ')}`);
assert.ok(!/\b(?:[1-9]\d{2,})\+?\s+(?:verified\s+)?suppliers\b/i.test(html), 'Possible fabricated supplier metric found');
assert.ok(!/testimonial/i.test(html), 'Unexpected testimonial content found');
assert.ok(html.includes('https://unon4all.github.io/nigeriamart-website/'), 'GitHub Pages canonical URL missing');
assert.ok(!html.includes('%VITE_CANONICAL_URL%'), 'Unresolved canonical placeholder found');
assert.ok(html.includes('/nigeriamart-website/favicon.png'), 'Base-aware favicon path missing');
assert.ok(html.includes('href="/nigeriamart-website/privacy.html"'), 'Project Pages privacy link missing');
assert.match(sourceCss, /\.site-nav\s*\{[^}]*position:\s*sticky/s, 'Primary navigation must remain sticky so it cannot overlap initial hero content');
assert.doesNotMatch(sourceCss, /\.site-nav\s*\{[^}]*position:\s*fixed/s, 'Primary navigation regressed to fixed positioning');
assert.match(sourceCss, /\.hero\s*\{[^}]*height:\s*auto/s, 'Hero must remain content-driven to prevent short-viewport clipping');
console.log(`PASS: survey links, Pages base/canonical paths, early-stage labels, internal anchors, reduced motion, sticky-nav hero clearance, and no scale/testimonial claims. ${ids.size} anchored sections checked.`);
